### ISSUE TITLE
Download link to mod in taleworlds forum is broken. Please Upload full release on github (latest stable and latest testing) PLEASE! I BEG YOU!

### ISSUE THREAD

**Issue by WHYDONTYOULIKETHEPIECEAPIE** [Leifdin/Silverstag#32]
Moddb version of silverstag is completely outdated and broken- can not function with latest warband. I tried grabbing the latest 30.2 testing from the google drive link in the taleworlds forums but it just says "Google Drive can't scan this file for viruses. silverstag-0.30.2-testing.7z (516M) is too large for Google to scan for viruses. Would you still like to download this file?" and a button that says "download anyway"
the whole download google site link is in japanese besides a few things (not a problem I'm just saying what I notice) and when I click the button "download anyway" the website just reloads and nothing downloads.

AhhhhhhhhhhhhhhhhhhhhHHH!!!!!!!!!!!!

**Comment by Leifdin** [comment]
The link should be working now.
